<template>
    <div class="block">
        <h2>Block {{ block.Index }}</h2>
        <p><strong>Hash:</strong> {{ block.Hash }} <em>(This is a unique identifier for this block, generated by hashing the block's contents)</em></p>
        <p><strong>Data:</strong> {{ block.Data }} <em>(This is the data contained in the block. In a real blockchain, it could be a transaction or a smart contract)</em></p>
        <p><strong>PrevHash:</strong> {{ block.PrevHash }} <em>(This is the hash of the previous block in the blockchain. It ensures the integrity of the blockchain by making it difficult to alter existing blocks)</em></p>
    </div>
</template>

<script>
export default {
    props: {
        block: {
            type: Object,
            required: true,
            validator: function (object) {
                return 'Index' in object && 'Hash' in object && 'Data' in object && 'PrevHash' in object;
            }
        }
    }
}
</script>

<style scoped>
.block {
    border: 1px solid #eee;
    padding: 20px;
    margin-bottom: 20px;
}
</style>
